[package]
name = "mongokit-binding"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Mamba interface for mongokit under mambalibs.mongo"

[lib]
name = "mongokit_binding"
crate-type = ["rlib"]

[dependencies]
mongokit = { path = ".." }
mamba-registry = { path = "../../../crates/mamba-registry" }
linkme.workspace = true
