[package]
name = "mambalibs-http-binding"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Mamba interface for mambalibs.http"

[lib]
name = "mambalibs_http_binding"
crate-type = ["rlib"]

[dependencies]
mambalibs-http = { path = ".." }
mambalibs-di = { path = "../../dikit" }
mambalibs-di-binding = { path = "../../dikit/binding" }
schema-mamba = { path = "../../../crates/schema-mamba" }
mamba-registry = { path = "../../../crates/mamba-registry" }
linkme.workspace = true

# Client-side HTTP bindings backed by mambalibs_http::client.
tokio.workspace = true
once_cell.workspace = true
serde_json.workspace = true
reqwest.workspace = true
