[package]
name = "arraykit-binding"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Mamba interface for arraykit under mambalibs.array"

[lib]
name = "arraykit_binding"
crate-type = ["rlib"]

[dependencies]
arraykit = { path = ".." }
mamba-registry = { path = "../../../crates/mamba-registry" }
linkme.workspace = true
