[package]
name = "pgkit-binding"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Mamba interface for pgkit under mambalibs.pg"

[lib]
name = "pgkit_binding"
crate-type = ["rlib"]

[dependencies]
mamba-registry = { path = "../../../crates/mamba-registry" }
pg = { path = "../pg" }
linkme.workspace = true
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres"] }
tokio.workspace = true
serde_json.workspace = true
thiserror.workspace = true
once_cell.workspace = true
