[package]
name = "cryptokit-binding"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Mamba interface for cryptokit under mambalibs.crypto"

[lib]
name = "cryptokit_binding"
crate-type = ["rlib"]

[dependencies]
cryptokit = { path = ".." }
mamba-registry = { path = "../../../crates/mamba-registry" }
linkme.workspace = true
