[package]
name = "mambalibs-di-binding"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Mamba interface for mambalibs.di"

[lib]
name = "mambalibs_di_binding"
crate-type = ["rlib"]

[dependencies]
mambalibs-di = { path = ".." }
mamba-registry = { path = "../../../crates/mamba-registry" }
linkme.workspace = true
