[package]
name = "scikit-binding"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Mamba interface for scikit under mambalibs.sci"

[lib]
name = "scikit_binding"
crate-type = ["rlib"]

[dependencies]
scikit = { path = ".." }
mamba-registry = { path = "../../../crates/mamba-registry" }
linkme.workspace = true
