[package]
name = "plotkit-binding"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Mamba interface for plotkit under mambalibs.plot"

[lib]
name = "plotkit_binding"
crate-type = ["rlib"]

[dependencies]
plotkit = { path = ".." }
mamba-registry = { path = "../../../crates/mamba-registry" }
linkme.workspace = true
