from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from som.python_seed_inventory import PythonSeedInventoryError, stage_python_seed_inventory


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _family(root: Path, name: str = "family-a", *, bad_hash: bool = False) -> None:
    parent = root / "proposed-fixtures" / name
    candidates = []
    hashes = {}
    for index in range(7):
        candidate = "gold" if index == 0 else f"miss-{index}"
        module = f"{candidate}/candidate.py"; test = f"{candidate}/test_behavior.py"
        _write(parent / module, f"VALUE = {index}\n")
        _write(parent / test, "from candidate import VALUE\ndef test_candidate():\n    assert VALUE == 0\n")
        hashes[module] = hashlib.sha256((parent / module).read_bytes()).hexdigest()
        hashes[test] = hashlib.sha256((parent / test).read_bytes()).hexdigest()
        candidates.append({"id": candidate, "module": module, "test": test, "support_paths": []})
    if bad_hash:
        hashes["gold/candidate.py"] = "0" * 64
    _write(parent / "family.json", json.dumps({
        "family_id": name, "domain": "python", "capability": "pytest.unit", "semantic_lineage": f"lineage-{name}",
        "source_policy": "CC0-1.0-authored", "status": "draft", "requirement": "Value must be zero.",
        "skeleton": "A fixed module exposes VALUE.", "candidates": candidates, "source_hashes": hashes,
    }))


def test_stages_inventory_without_formal_rows_or_oracle(tmp_path: Path) -> None:
    root = tmp_path / "source"; _family(root)
    result = stage_python_seed_inventory(fixture_root=root, output_root=tmp_path / "stage", run_oracle=False)
    assert result == {"status": "staged_not_formal", "families": 1, "candidates": 7, "oracle_executed": False, "output_root": str((tmp_path / "stage").resolve())}
    inventory = json.loads((tmp_path / "stage" / "inventory.json").read_text())
    item = inventory["families"][0]
    assert item["state"] == "A fixed module exposes VALUE."
    assert len(item["candidates"]) == 7
    assert item["candidates"][0]["kind"] == "gold"
    assert item["candidates"][1]["kind"] == "near_miss"
    assert not list((tmp_path / "stage").glob("*-python.jsonl"))
    assert json.loads((tmp_path / "stage" / "manifest.json").read_text())["training_authorized"] is False


def test_rejects_changed_seed_bytes_before_oracle(tmp_path: Path) -> None:
    root = tmp_path / "source"; _family(root, bad_hash=True)
    with pytest.raises(PythonSeedInventoryError, match="source hash changed"):
        stage_python_seed_inventory(fixture_root=root, output_root=tmp_path / "stage", run_oracle=False)


def test_refuses_to_replace_staged_inventory(tmp_path: Path) -> None:
    root = tmp_path / "source"; _family(root)
    output = tmp_path / "stage"; output.mkdir(); _write(output / "keep", "keep")
    with pytest.raises(PythonSeedInventoryError, match="refusing to overwrite"):
        stage_python_seed_inventory(fixture_root=root, output_root=output, run_oracle=False)


def test_staged_inventory_is_accepted_by_materializer_inventory_schema(tmp_path: Path) -> None:
    from som.python_corpus_materializer import _load_inventory
    root = tmp_path / "source"; _family(root)
    output = tmp_path / "stage"
    stage_python_seed_inventory(fixture_root=root, output_root=output, run_oracle=False)
    loaded = _load_inventory(root, output / "inventory.json")
    assert set(loaded) == {"family-a"}
    assert [item["kind"] for item in loaded["family-a"]["candidates"]] == ["gold", *["near_miss"] * 6]


def test_fixed_oracle_ignores_generated_cache_files(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A generated bytecode file is not copied into the fixed oracle sandbox."""
    import som.python_corpus as corpus

    root = tmp_path / "source"
    _family(root)
    cache = root / "proposed-fixtures" / "family-a" / "gold" / "__pycache__" / "candidate.cpython-312.pyc"
    _write(cache, "generated cache only")
    copied_cache_paths: list[Path] = []
    original_copytree = corpus.shutil.copytree

    def observing_copytree(source: object, destination: object, *args: object, **kwargs: object) -> object:
        result = original_copytree(source, destination, *args, **kwargs)
        copied_cache_paths.append(Path(destination) / cache.relative_to(root))
        return result

    monkeypatch.setattr(corpus.shutil, "copytree", observing_copytree)
    result = stage_python_seed_inventory(fixture_root=root, output_root=tmp_path / "stage", run_oracle=True)
    assert result["oracle_executed"] is True
    assert copied_cache_paths
    assert all(not item.exists() for item in copied_cache_paths)
